import { useEffect, useState } from "react";
import { useAuth } from "@clerk/clerk-react";
import { toast } from "sonner";
import { Download, Search } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

import { VideoCardSkeleton } from "../components/VideoCardSkeleton";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

interface Job {
  id: string;
  prompt: string;
  title?: string;
  status: string;
  createdAt: string;
  duration?: number;
  videoUrl?: string;
}

interface JobsResponse {
  jobs: Job[];
  total: number;
  limit: number;
  offset: number;
}

export default function Gallery() {
  const { getToken } = useAuth();
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const limit = 10;

  // Debounce search
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(search);
      setPage(1); // Reset page on search change
    }, 500);
    return () => clearTimeout(timer);
  }, [search]);

  useEffect(() => {
    fetchJobs();
  }, [getToken, page, debouncedSearch]);

  const fetchJobs = async () => {
    try {
      setLoading(true);
      const offset = (page - 1) * limit;

      const queryParams = new URLSearchParams({
        limit: limit.toString(),
        offset: offset.toString(),
      });
      if (debouncedSearch) {
        queryParams.append("search", debouncedSearch);
      }

      const response = await fetch(
        `${API_URL}/jobs/public?${queryParams.toString()}`,
        {
          headers: {
            "Content-Type": "application/json",
          },
        },
      );

      if (!response.ok) {
        throw new Error("Failed to fetch jobs");
      }

      const data: JobsResponse = await response.json();
      setJobs(data.jobs);
      console.log(data);
      setTotalPages(Math.ceil(data.total / limit));
    } catch (error) {
      console.error(error);
      toast.error("Failed to load your gallery");
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (
    id: string,
    prompt: string,
    e: React.MouseEvent,
  ) => {
    e.preventDefault();
    e.stopPropagation();
    try {
      // Use public stream or check if we need token?
      // For now public stream should work if backend allows or we fetch token if logged in.
      // Assuming public download for gallery for now or using getToken if available.

      const response = await fetch(`${API_URL}/video/stream/${id}`, {});

      if (!response.ok) throw new Error("Download failed");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `manim-${prompt.slice(0, 20).replace(/\s+/g, "-")}.mp4`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error(error);
      toast.error("Failed to download video");
    }
  };

  return (
    <div className="min-h-screen bg-stone-50 pt-24 px-4 sm:px-8 pb-12 transition-colors duration-300">
      <div className="max-w-7xl mx-auto space-y-8">
        {/* Header Section */}
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          <div>
            <h1 className="text-3xl font-funnel font-medium text-stone-900">
              Community Showcase
            </h1>
            <p className="text-stone-500 mt-1">
              Explore animations generated by our community
            </p>
          </div>

          <div className="relative w-full md:w-96">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-stone-400" />
            <input
              type="text"
              placeholder="Search animations..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 bg-white border border-stone-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-stone-400 transition-all"
            />
          </div>
        </div>

        {/* Gallery Grid */}
        {loading && jobs.length === 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {[...Array(8)].map((_, i) => (
              <VideoCardSkeleton key={i} />
            ))}
          </div>
        ) : (
          <>
            {jobs.length === 0 ? (
              <div className="text-center py-24 bg-white rounded-2xl border border-stone-100 shadow-sm">
                <p className="text-stone-400">No animations found</p>
                {search && (
                  <button
                    onClick={() => setSearch("")}
                    className="text-blue-600 mt-2 hover:underline"
                  >
                    Clear search
                  </button>
                )}
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                <AnimatePresence>
                  {jobs.map((job) => (
                    <motion.div
                      key={job.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.95 }}
                      className="group bg-white rounded-xl overflow-hidden border border-stone-100 shadow-sm hover:shadow-md transition-all duration-300"
                    >
                      <div className="relative aspect-video bg-stone-900">
                        {job.status === "completed" ? (
                          <video
                            src={`${API_URL}/video/stream/${job.id}`}
                            className="w-full h-full object-cover"
                            controls
                            preload="metadata"
                          />
                        ) : (
                          <div className="w-full h-full flex items-center justify-center text-stone-500 text-sm">
                            {job.status}
                          </div>
                        )}

                        <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                          <button
                            onClick={(e) =>
                              handleDownload(job.id, job.prompt, e)
                            }
                            className="p-1.5 bg-black/50 text-white rounded-md hover:bg-black/70 backdrop-blur-sm transition-colors"
                            title="Download"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                        </div>
                      </div>

                      <div className="p-4">
                        <h3
                          className="font-medium text-stone-900 truncate"
                          title={job.title || job.prompt}
                        >
                          {job.title || job.prompt}
                        </h3>
                        <div className="flex justify-between items-end mt-2">
                          <p className="text-xs text-stone-400 line-clamp-2 flex-1 mr-4">
                            {new Date(job.createdAt).toLocaleDateString()}
                          </p>
                          <span
                            className={`text-[10px] px-2 py-1 rounded-full uppercase tracking-wider font-semibold ${
                              job.status === "completed"
                                ? "bg-green-100 text-green-700"
                                : job.status === "failed"
                                  ? "bg-red-100 text-red-700"
                                  : "bg-yellow-100 text-yellow-700"
                            }`}
                          >
                            {job.status}
                          </span>
                        </div>
                      </div>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
            )}

            {/* Pagination Controls */}
            {totalPages > 1 && (
              <div className="flex justify-center gap-2 mt-12">
                <button
                  disabled={page === 1}
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  className="px-4 py-2 rounded-lg border border-stone-200 disabled:opacity-50 hover:bg-stone-50 transition-colors"
                >
                  Previous
                </button>
                <span className="px-4 py-2 text-stone-600">
                  Page {page} of {totalPages}
                </span>
                <button
                  disabled={page === totalPages}
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  className="px-4 py-2 rounded-lg border border-stone-200 disabled:opacity-50 hover:bg-stone-50 transition-colors"
                >
                  Next
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
